-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 18, 2021 at 12:14 PM
-- Server version: 10.1.30-MariaDB
-- PHP Version: 5.6.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `testing`
--

-- --------------------------------------------------------

--
-- Table structure for table `post`
--

CREATE TABLE `post` (
  `id` mediumint(8) UNSIGNED NOT NULL,
  `post_title` text,
  `post_description` text,
  `author` varchar(255) DEFAULT NULL,
  `datetime` datetime DEFAULT NULL,
  `post_image` varchar(150) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `post`
--

INSERT INTO `post` (`id`, `post_title`, `post_description`, `author`, `datetime`, `post_image`) VALUES
(1, 'Insert Update Delete using Stored Procedure in Mysql and PHP - 1', 'In Video we have learn how to fetch data from database and Insert data to database using stored procedure in Mysql and PHP. Part 2 - https://www.youtube.com/watch?v=qkN-LLStTdU Part 3 - https://www.youtube.com/watch?v=dY_AhFsg6vM', 'Webslesson', '2018-11-25 04:00:00', 'insert-update-delete-using-stored-procedure-in-mysql-and-php-1.jpg'),
(2, 'Insert Update Delete using Stored Procedure in Mysql and PHP - 2', 'In this Video we have to learn how to fetch single data from database and display data in form using stored procedure and update that data using stored procedure in MySql and PHP.', 'Webslesson', '2018-11-26 21:00:00', 'insert-update-delete-using-stored-procedure-in-mysql-and-php-2.jpg'),
(3, 'Insert Update Delete using Stored Procedure in Mysql and PHP - 3 ', 'In this Video we have to learn how to delete single data from database using stored procedure and update that data using stored procedure in MySql and PHP.', 'Webslesson', '2019-01-27 06:00:00', 'insert-update-delete-using-stored-procedure-in-mysql-and-php-3.jpg'),
(4, 'Auto Refresh Div Content Using jQuery and AJAX', 'How to do Auto Load and Refresh  Div every Seconds with jQuery and Ajax. So today I needed content in a div to refresh every seconds, so I used AJAX shorthand method .load() and setInterval() and then simply sets a call for the data every seconds. So every second div content will refresh automatically.', 'Webslesson', '2018-11-30 22:00:00', 'auto-refresh-div-content-using-jquery-and-ajax.jpg'),
(5, 'How to generate simple random password in php?', 'For Generating random password in php I am using two string function. First is str_shuffle function and second is substr function.', 'Webslesson', '2018-12-03 10:00:00', 'how-to-generate-simple-random-password-in-php.jpg'),
(6, 'Rename uploaded image in php with upload validation', 'In this video we learn how to upload image file, rename uploaded file, file upload validation like file is selected or not, file is with proper extension or not, size of file etc.', 'Webslesson', '2018-12-03 03:00:00', 'rename-uploaded-image-in-php-with-upload-validation.jpg'),
(7, 'How to check Username availability using php, Ajax, Jquery and Mysql', 'In this video, we are going to learn how to check username available or not using php, mysql, Ajax and Jquary. If you want to restrict duplicate username then this video will helpful to you. http://www.webslesson.info/2016/02/how-to-check-username-availability-in.html', 'Webslesson', '2018-12-05 19:00:00', 'how-to-check-username-availability-using-php-ajax-jquery-and-mysql.jpg'),
(8, 'How To Insert Data Using Stored Procedure In Php Mysql', 'In this video, we will learn how to call stored procedures using PHP. Stored procedures can increase website performance and decrease database access traffic.', 'Webslesson', '2018-12-05 17:00:00', 'how-to-insert-data-using-stored-procedure-in-php-mysql.jpg'),
(9, 'How to merge two PHP JSON Array', 'In this video we are going to learn about how to merge two or more JSON array.', 'Webslesson', '2018-12-05 03:00:00', 'how-to-merge-two-php-json-array.jpg'),
(10, 'How to check Multiple value exists in an Array in PHP', 'In this video I show you how to check multiple value exists or not in php array. Because for checking single value we can use in_array() function but there no php function for checking multiple value in php array. So I make this custom array function for checking multiple value in php array. This my function.\r\n\r\nfunction multiple_in_array($search, $source)\r\n{\r\nreturn (count(array_intersect($search, $source)) == count($search));\r\n}', 'Webslesson', '2018-12-07 21:00:00', 'how-to-check-multiple-value-exists-in-an-array-in-php.jpg'),
(11, 'Create Simple Image using PHP', 'Hello Friends today we learn how to create simple Image using PHP GD Library. This type of generating dynamic image using php can be useful for many purpose e.g. Captcha Code Image http://www.webslesson.info/2016/01/create-simple-image-using-php.html', 'Webslesson', '2019-02-08 02:00:00', NULL),
(12, 'How to Add Watertext or Watermark to an Image using PHP GD Library', 'In this video I will show you how to add watertext or watermark on to Image using PHP GD Library. On Most of the E-Commerce site we can see that most of the product image has come with some watertext or watermark on that. So, It is very useful video to learn for web development. For Text tutorial of this video available here - http://www.webslesson.info/2016/02/how-to-insert-watermark-on-to-image-using-php-gd-library.html', 'Webslesson', '2018-12-08 20:00:00', 'how-to-add-watertext-or-watermark-to-an-image-using-php-gd-library.jpg'),
(13, 'Make SEO Friendly or Clean Url in PHP using .htaccess', 'In this video we going to learn how to create semantic or pretty url in php using .htaccess file. SEO Friendly Url is most important in SEO, it will help in increase presence on search engine, fast indexing our content and incease ranking on search engine. So, Clean slug urls are very useful for our website.', 'Webslesson', '2018-12-10 06:00:00', 'make-seo-friendly-or-clean-url-in-php-using-htaccess.jpg'),
(14, 'Live Table Add Edit Delete using Ajax Jquery in PHP Mysql', 'In this Video, we learn live table Insert, Update, Delete, Fetch data from mysql database using Ajax Jquary in php without page refresh. For this I use html5 contenteditable attribute for table column editable. For source code - http://www.webslesson.info/2016/02/live-table-add-edit-delete-using-ajax-jquery-in-php-mysql.html', 'Webslesson', '2018-12-10 05:00:00', 'live-table-add-edit-delete-using-ajax-jquery-in-php-mysql.jpg'),
(15, 'Export MySQL data to Excel in PHP - PHP Tutorial', 'In this PHP Video tutorial we are going to learn how to export mysql data from web page to excel sheet in php. This things is very important in big enterprise application where lots of data are there to make excel file from that data. For Source code - http://www.webslesson.info/2016/02/export-mysql-data-to-excel-in-php-php-tutorial.html', 'Webslesson', '2018-12-12 16:00:00', NULL),
(16, 'Load More Data using Ajax Jquery with PHP MySql', 'Jquery Ajax Load more button. Load More button Jquery Example. Load more Functionality in PHP. Load More Jquery Example. Load More Data on Button click using JQuery. Load Data using Ajax in PHP. Ajax Load more data from Mysql in PHP using Ajax. For Source Code - http://www.webslesson.info/2016/02/how-to-load-more-data-using-ajax-jquery.html', 'Webslesson', '2018-12-14 18:00:00', NULL),
(17, 'Dynamically Add / Remove input fields in PHP with Jquery Ajax', 'Add or Remove input fields dynamically with Ajax JQuery. Add Input Field using Jquery. How to Add / Remove textbox dynamically with Jquery. Javascript add input fields dynamically. Dynamically add input fields and submit to database with Jquery and PHP. Add Field dynamically to form in jquery and php. Dynamically Add form fields PHP. Source Code -  http://www.webslesson.info/2016/02/dynamically-add-remove-input-fields-in-php-with-jquery-ajax.html', 'Webslesson', '2018-12-15 15:00:00', NULL),
(18, 'PHP Introduction - PHP Tutorial for Beginner', 'Introduction to PHP - First lesson in PHP Tutorial for beginners. In this lesson we will learn what is php. Application of PHP in web development. How can we use php in web development etc.', 'Webslesson', '2018-12-17 04:00:00', NULL),
(19, 'PHP Variables - Echo, Print statement - PHP Tutorial for Beginner', 'In this we will describe you a Basic PHP variables. There three types of variable scope. Local, Global and Static variable. There are two ouput statement in php. Echo and Print statement.', 'Webslesson', '2018-12-17 12:00:00', NULL),
(20, 'How to Import Excel Data into MySQL Database using PHP', 'This video cover read excel file and inserted into mysql table using php language. php tutorial, php, phpexcel, class, phpexcel tutorial, mysql, php mysql, php mysql tutorial, mysql database, microsoft excel, excel mysql, import excel, data, database, insert, query, import excel file data in mysql, upload ecxel file in mysql, code to import excel data in mysql database, upload excel file, xls file, website development, tutorial, mysqli, import, spreadsheet, csv, export data, save file, php file. Source Code - http://www.webslesson.info/2016/03/read-excel-data-and-insert-into-mysql-database-using-php.html', 'Webslesson', '2018-12-17 04:00:00', NULL),
(21, 'Convert Currency using Google Finance in PHP', 'How to Convert Currency using Google Finance in PHP. Live currency convert using Google finance in php. Use Google finance calculator to convert currency with php. Convert currency using google finance calculator in php. PHP Tutorials Currency Conversion using Google Calculator. Convert Currency using Google Finance in PHP. Source Code - http://www.webslesson.info/2016/03/how-to-convert-currency-using-google-finance-in-php.html', 'Webslesson', '2018-12-19 19:00:00', NULL),
(22, 'Dynamic Dependent Select Box using Jquery and Ajax in PHP', 'Dynamic Dependent Select Box using jQuery, Ajax and PHP. Select Box Change Dependent Options dynamically. jQuery Dependent DropDown List – Countries and States, Categories and Sub Categories. Dynamic Select Option Menu Using Ajax And PHP. Dynamic drop down box from mysql. Dynamically generate a select list with jQuery, AJAX & PHP. Auto-populating Select Boxes using jQuery & AJAX. Dynamic Select Boxes With PHP MySQL jQuery - Without Page Refresh. Source Code - http://www.webslesson.info/2016/03/dynamically-generate-a-select-list-with-jquery-ajax-php.html', 'Webslesson', '2018-12-20 21:00:00', NULL),
(23, 'How to use HTML tag into PHP tag', 'In this PHP beginner Video tutorial we are going to learn how to write html tag into PHP tag.', 'Webslesson', '2018-12-22 04:00:00', NULL),
(24, 'How to use PHP code into HTML Tag', 'In this PHP Video tutorial we are going to learn how to write PHP code into html Tag.', 'Webslesson', '2018-12-23 02:00:00', NULL),
(25, 'How to get Multiple Checkbox values in php', 'This video relate to PHP Multiple Checkbox Array, Get $_POST from multiple checkboxes, Get Values of Multiple Checked Checkboxes , How to handle multiple Checkboxes Values in a FORM using PHP, Get Multiple Checkbox Values in PHP, How to get multiple checkbox value in PHP, Get Value from multiple checkbox in PHP, Storing multiple checkbox values, PHP Multiple Checkbox Array Handling, Handling checkbox in a PHP form processor. Source Code -  http://www.webslesson.info/2016/03/how-to-get-multiple-checkbox-values-in-php.html', 'Webslesson', '2018-12-24 19:00:00', NULL),
(26, 'Ajax Live Data Search using Jquery PHP MySql', 'PHP AJAX Live Search, Ajax Live Search With PHP and MySQL, Live search in php using jquery ajax without reloading page, How To Integrate Live Search In PHP And MySQL With JQuery, Ajax Live Search - PHP Tutorial, Ajax Search Box in PHP and MySQL, mysql - Livesearch php and ajax, How To Create Ajax Search Using PHP Jquery and Mysql. Source code - http://www.webslesson.info/2016/03/ajax-live-data-search-using-jquery-php-mysql.html', 'Webslesson', '2018-12-25 04:00:00', NULL),
(27, 'Auto Save Data using Ajax, Jquery, PHP and Mysql', 'This video relate to Automatically Save data after specific time Interval using Ajax JQuery MySql & PHP. This type of feature you mostly shown wordpress post. In wordpress post are automatically saved into database on regular time interval. This things are describe in this video. If you are familiar with wordpress then you can easily understand what we are going to learn. Source code - http://www.webslesson.info/2016/03/auto-save-data-using-ajax-jquery-php-and-mysql.html', 'Webslesson', '2018-12-25 15:00:00', NULL),
(28, 'How to Use Ajax with PHP for login with shake effect', 'This video relates to ajax PHP Login Page with Shake Animation Effect. Login Page with Shake Animation Effect using ajax. Ajax PHP Login Page with Shake Animation Effect. PHP Login Page With Shake Effect Like Wordpress. jQuery Form Shake Effect on Invalid Entry. Source Code - http://www.webslesson.info/2016/03/how-to-use-ajax-with-php-for-login-with-shake-effect.html', 'Webslesson', '2018-12-25 03:00:00', NULL),
(29, 'How to get Time Ago like Facebook in PHP', 'Time Ago In PHP Like Facebook, Converting timestamp to time ago in PHP e.g 1 day ago, 2 days ago…, facebook style time ago function, Time Ago PHP Function, Facebook Style time ago, PHP Function: Posted Time Ago – Facebook Style, PHP Time Ago Script by webslesson, Facebook-like time ago with PHP, How to: Create facebook or twitter style x-time ago date format in php. Source Code - http://www.webslesson.info/2016/03/facebook-style-time-ago-function-using-php.html', 'Webslesson', '2018-12-27 17:00:00', NULL),
(30, 'Upload Resize Image using Ajax Jquery PHP without Page Refresh', 'This video cover Ajax Upload And Resize An Image Using PHP & jQuery, Upload and Resize an Image with PHP, Ajax Upload and Resize an Image with PHP, Ajax Image Upload and Resize with jQuery and PHP, PHP Image upload and generate thumbnail using ajax, PHP Ajax Image Upload without refreshing page using jQuery, How to upload an image and generate thumbnail without refreshing the page using jQuery, ajax and php. Source Code - http://www.webslesson.info/2016/03/upload-resize-image-using-ajax-jquery-php-without-page-refresh.html', 'Webslesson', '2019-01-28 05:00:00', NULL),
(31, 'How to Search for Exact word match FROM String using LIKE', 'How to search exact word from mysql database table column string using wildcards RLIKE operator. It search exact word from given string in column, if exact word found in cloumn string then it will return data from mysql database. It\'s an advance turorial on mysql database.', 'Webslesson', '2018-12-28 06:00:00', NULL),
(32, 'How To Create A Show Password Button using Jquery', 'In this video we will learn how to show and hide input password field using jquery. We can easily toggling password field to textbox field and textbox field to password field using click on button. I have used jquery attr() method in this video. Source Code - http://www.webslesson.info/2016/03/how-to-create-a-show-password-button-using-jquery.html', 'Webslesson', '2018-12-29 20:00:00', NULL),
(33, 'Use Marquee HTML tag with PHP and Mysql - PHP Tutorial', 'In this video I show you to display dynamic content in marquee html tag using php and mysql. With the help of marquee we can display latest post or news in text scrolling format. Source Code - http://www.webslesson.info/2016/03/use-marquee-tag-with-php-and-mysql-php.html', 'Webslesson', '2018-12-29 05:00:00', NULL),
(34, 'How to Enter PHP Array within MySQL Database', 'In this video I will show you how to insert php array into mysql table. Insert array into MySQL database with PHP. How to insert array of data into mysql using php. Inserting An Array into a MySQL Database Table. Insert Multiple Rows Into MySQL The Right Way With PHP. Source Code - http://www.webslesson.info/2016/03/how-to-enter-php-array-within-mysql-database.html', 'Webslesson', '2018-12-30 08:00:00', NULL),
(35, 'Use Ajax with Jquery in PHP to check Session Expired', 'When user open website in multiple tab and he logout from one table and website open other tab. So We want to display alert message with Your Session has been expired in that tab where website is open. This things are learn into this php video tutorial. Source Code - http://www.webslesson.info/2016/03/use-ajax-with-jquery-in-php-to-check-session-expired.html', 'Webslesson', '2018-12-30 16:00:00', NULL),
(36, 'Ajax Delete multiple data with checkboxes in PHP Jquery Mysql', 'Delete multiple table row on checked checkbox in php with Ajax Jquery. With help of Ajax Jquery user can remove multiple table row on one single click with change background color of selected table row and fade out jquery effect in php mysql without page refresh. Source Code - http://www.webslesson.info/2016/04/ajax-delete-multiple-data-with-checkboxes-in-php-jquery-mysql.html', 'Webslesson', '2019-01-01 03:00:00', NULL),
(37, 'Automatic Logout after 15 minutes of user Inactivity using PHP', 'How to destroy session in php if user inactive since last 15 minutes. If user inactive for last 15 minutes and after he refresh page then he will automatically logout from website and redirect to login page. Source Code - http://www.webslesson.info/2016/04/automatic-logout-after-15-minutes-of.html', 'Webslesson', '2019-01-01 16:00:00', NULL),
(38, 'PHP Login Script with Remember me Login Details', 'This video show you how to use remember me functionality in PHP Login script with help of $_COOKIE array variable to store user details like username or email and password in to this $_COOKIE. When user type login details and login into website then it\'s details are store in $_COOKIE and when user again come back for login then login form will automatically filled. Source Code - http://www.webslesson.info/2016/04/php-login-code-with-remember-me-login-details.html', 'Webslesson', '2019-01-02 04:00:00', NULL),
(39, 'Arithmetic Operators - PHP Beginner Tutorial', 'This Video show Arithmetic Operators in PHP. Arithmetic Operators like Addition, Subtraction, Multiplication, Division, Modulus Operator.', 'Webslesson', '2019-01-02 16:00:00', NULL),
(40, 'Shorten Dynamic Comment with Jquery PHP Mysql', 'In this video you can find how to shorten dynamic comment by using Jquery PHP Mysql. This my video Tutorial on Advance PHP and Jquery. Source Code - http://skillinfinity.com/blog/topics/php/facebook-type-shorten-dynamic-comment-with-jquery-php-mysql', 'Webslesson', '2019-01-03 05:00:00', NULL),
(41, 'If, If else Conditional Statement in PHP', 'In this PHP Beginner Tutorial video I will show you If and If else conditional statement in PHP.', 'Webslesson', '2019-01-03 17:00:00', NULL),
(42, 'If, Else if Conditional statement in PHP', 'In this PHP Beginner Tutorial video we will learn If, Else if Conditional statement in PHP.', 'Webslesson', '2019-01-04 06:00:00', NULL),
(43, 'How to Create Zip File using PHP Code', 'In this php video tutorial, you can find how to create zip file in php code. Selected file will convert to zip file formate with the help of php_zip php extension. Source Code - http://www.webslesson.info/2016/04/how-to-create-zip-file-using-php-code.html', 'Webslesson', '2019-01-05 22:00:00', NULL),
(44, 'Increment / Decrement Operator - PHP Beginner Tutorial', 'In this Beginners PHP Video Tutorials, I will teach you Increment / Decrement Operator in PHP.', 'Webslesson', '2019-01-05 04:00:00', NULL),
(45, 'How to Generate CSV File from PHP Array', 'In this video you can learn how to generate CSV(Comma-Separated Values) file from PHP Array. Suppose friends if you have data in array and you do not want to enter into mysql table and you want the user directly download that data into csv formate. This things are learn into this video. Source Code - http://www.webslesson.info/2016/04/how-to-generate-csv-file-from-php-array.html', 'Webslesson', '2019-01-07 04:00:00', NULL),
(46, 'Upload CSV and Insert Data into Mysql Using PHP', 'You can find how import data from csv file and insert into mysql table in php. Here I show you user first upload csv file and with help of php code we can get csv file data and make mysql insert query and insert that data to mysql table. Source Code - http://www.webslesson.info/2016/04/upload-csv-and-insert-data-into-mysql-using-php.html', 'Webslesson', '2019-01-07 17:00:00', NULL),
(47, 'Multiple Images Upload using PHP Jquery Ajax', 'How to upload multiple images without page refresh by using PHP with the help of Jquery with Ajax. If you want to learn how php can upload multiple images with help of Ajax Jquery. Source Code - http://www.webslesson.info/2016/04/multiple-images-upload-using-php-jquery-ajax.html', 'Webslesson', '2019-01-08 07:00:00', NULL),
(48, 'Fetch JSON Data & Insert into Mysql table in PHP', 'In this video you can learn how to insert multiple json data into MySql Database in PHP. I will show you how to get first JSON Data from external json data file and then after insert them to Mysql Database using PHP Script. Source Code - http://www.webslesson.info/2016/04/get-multiple-json-data-insert-into-mysql-database-in-php.html', 'Webslesson', '2019-01-09 17:00:00', NULL),
(49, 'Comparison Operators - PHP Beginner Tutorial', 'In this PHP Beginner Video Tutorial, you can find Comparison Operators in PHP Programming Language. In Comparison Operators, you can find double equal to, identical like triple equal to, not equal to, greater than, greater than equal to, less than, less than equal to operator you can learn.', 'Webslesson', '2019-01-09 03:00:00', NULL),
(50, 'Create Simple Progress bar using HTML, CSS with jquery', 'How to create simple progress bar using css with jquery, you can learn this things in this video. In css part I have use transition effect for increase width of span tag very smoothly and In Jquery I have use setInterval() method for increase width of span tag and if width greater than 100% than at that time I have use clearInterval() method for clear the interval timer set by setInterval() method. Source Code - http://www.webslesson.info/2016/04/create-simple-progress-bar-using-css-with-jquery.html', 'Webslesson', '2019-01-10 18:00:00', NULL),
(51, 'Append Data to JSON File using PHP', 'How to Append form data to JSON File in PHP Programming Language. I have create one HTML form, I want to add the form data into one json file. For this I have use file_get_contents(), json_decode(), json_encode() and file_put_contents(). Source Code - http://www.webslesson.info/2016/04/append-data-to-json-file-using-php.html', 'Webslesson', '2019-01-10 02:00:00', NULL),
(52, 'Form Submit with Fade Out Message using Jquery Ajax PHP', 'In this video you can show form submit with fade out message using Jquery Ajax in php. Source Code - http://www.webslesson.info/2016/04/form-submit-with-fade-out-message-using-jquery-ajax-php.html', 'Webslesson', '2019-01-11 19:00:00', NULL),
(53, 'String Operators - PHP Beginner Tutorial', 'In this PHP Beginner Video Tutorial, you can learn about string operators in php programming language. There are two operator. Concatenation Operator and Concatenation assignment Operator.', 'Webslesson', '2019-01-12 06:00:00', NULL),
(54, 'Load Records on Select box using Ajax Jquery Mysql and PHP', 'In this video you can learn how to load data from mysql database table when user change item from dropdown box, at that time it load related records of selected item. For this I have use php and mysql with jquery and Ajax. Source Code - http://www.webslesson.info/2016/04/load-records-on-select-box-using-ajax-jquery-mysql-and-php.html', 'Webslesson', '2019-01-14 19:00:00', NULL),
(55, 'Fetch Data from Two or more Table Join using PHP and MySql', 'In this video you can find how to merge two table data using inner join keyword and load that data on web page using php and mysql. Source Code - http://www.webslesson.info/2016/04/fetch-data-from-two-or-more-table-join-using-php-and-mysql.html', 'Webslesson', '2019-01-14 05:00:00', NULL),
(56, 'Convert Data from Mysql to JSON Formate using PHP', 'This video tutorial show you how to convert mysql data formate to JSON data formate using PHP. It simply fetch data from mysql database table and convert into JSON string format by using json_encode() function. Source Code - http://www.webslesson.info/2016/05/convert-data-from-mysql-to-json-formate-using-php.html', 'Webslesson', '2019-01-14 19:00:00', NULL),
(57, 'How to use Mysql View in PHP Code', 'In this video you can find how to create View in phpmyadmin and how to retrieve data from this view in php code. I also show how to update view and how to delete view in phpmyadmin. Source Code - http://www.webslesson.info/2016/05/how-to-use-mysql-view-in-php-code.html', 'Webslesson', '2019-01-16 03:00:00', NULL),
(58, 'Upload and Extract a Zip File in PHP', 'In this video you can find how to extract zip file in php. In this video I will show you upload zip file in upload folder after upload i will extract zip in upload folder after this I will copy all file from extracted folder to upload folder and remove zip file from upload folder and lastly remove extracted folder from upload file folder. Source Code - http://www.webslesson.info/2016/05/upload-and-extract-zip-file-in-php.html', 'Webslesson', '2019-01-16 19:00:00', NULL),
(59, 'Stylish Switch Button using CSS3 and Jquery', 'Hello friends In this video you can find How to iOS Style Switch Button using CSS3 and Jquery. iOS 7 style switches for your checkboxes. iOS 7 Style Smooth Toggle Buttons With jQuery and CSS3. Stylish Switch Button using CSS3 and Jquery. Source Code - http://www.webslesson.info/2016/05/stylish-switch-button-using-css3-and-jquery.html', 'Webslesson', '2019-01-17 06:00:00', NULL),
(60, 'How to create Spinner or Loaders with CSS3', 'In this video you can find how create simple spinner or loaders using css3. Before we have use gif image for showing page loading or display any process but after with the help of css3 we can easily create spinners or loaders. Source Code - http://www.webslesson.info/2016/05/how-to-create-spinner-or-loaders-with-css3.html', 'Webslesson', '2019-01-17 16:00:00', NULL),
(61, 'How to Auto Resize a textarea html field by jQuery', 'In this video you can find how to auto resize a textarea html field by using jquery. In Jquery I have used focus() and blur() event with animate() method of jquery. Source Code - http://www.webslesson.info/2016/05/how-to-auto-resize-a-textarea-html-field-by-jquery.html', 'Webslesson', '2019-01-18 08:00:00', NULL),
(62, 'Insert data into Table using OOPS in PHP', 'In this video you can learn how to use PHP Object Oriented Programming for Insert or Add data or item into MySql Table. If you are using OOPS in PHP then it will be become very simple to use and can do such function like Add or Insert data into mysql table. Source Code - http://www.webslesson.info/2016/07/php-oops-insert-data-into-mysql-database.html', 'Webslesson', '2019-01-18 19:00:00', NULL),
(63, 'Select or Fetch Data from Mysql Table using OOPS in PHP', 'In this video you can find how to retrieve data from mysql table using php object oriented programming concept and display data on webpage in table formate. Source Code - http://www.webslesson.info/2016/05/select-or-fetch-data-from-mysql-table-using-oops-in-php.html', 'Webslesson', '2019-01-19 05:00:00', NULL),
(64, 'Update or Edit Data from Mysql Table using OOPS in PHP', 'In this video you can find how to fetch single data and display that data in html form and after edit or update that data using php object oriented programming concept. Source Code - http://www.webslesson.info/2016/05/update-or-edit-data-from-mysql-table-using-oops-in-php.html', 'Webslesson', '2019-01-19 15:00:00', NULL),
(65, 'Delete Data from Mysql Table using OOP in PHP', 'In this video you can find how to use php object oriented programming for delete or remove records or data from mysql table. Source Code - http://www.webslesson.info/2016/05/delete-data-from-mysql-table-using-oop-in-php.html', 'Webslesson', '2019-01-19 07:00:00', NULL),
(66, 'PHP Login Script using OOP', 'In this video you can find how to use php object oriented programming for delete or remove records or data from mysql table. Source Code - http://www.webslesson.info/2016/05/delete-data-from-mysql-table-using-oop-in-php.html', 'Webslesson', '2019-01-21 04:00:00', NULL),
(67, 'How to load Product on price change using Ajax Jquery with PHP Mysql', 'This video will show you how to load product on price change on html5 input type range element by using Ajax function call with jquery, php and mysql. How to create Price Range Slider in jQuery & PHP with MySQL. Ajax Shopping Cart with PHP and jQuery. Source Code - http://www.webslesson.info/2016/05/how-to-load-product-on-price-change.html', 'Webslesson', '2019-01-22 20:00:00', NULL),
(68, 'How to Make Simple Pagination using PHP MySql', 'In this video you can learn how to create simple pagination using php mysql. Pagination is used when there is more data and I do not want to display on single page for this I have make pagination concept and divide records into different part. So We can reduce page loading page. Source Code - http://www.webslesson.info/2016/05/how-to-make-simple-pagination-using-php-mysql.html', 'Webslesson', '2019-01-22 05:00:00', NULL),
(69, 'PHP MySQL Insert record if not exists in table', 'In this video you can find how to use php mysql insert query for checking data already inserted or not. I have use insert query with sub query with where condition and not exits. I have simple use inner join in this insert query for checking data already inserted or not. Source Code - http://www.webslesson.info/2016/05/php-mysql-insert-record-if-not-exists-in-table.html', 'Webslesson', '2019-01-23 06:00:00', NULL),
(70, 'How to search multiple words at a time in Mysql php', 'In this video you can find how to search multiple words at a time in a row in Mysql php. Search multiple words in MySQL. Search for multiple keywords with php and mysql. Source Code - http://www.webslesson.info/2016/05/how-to-search-multiple-words-at-a-time-in-mysql-php.html', 'Webslesson', '2019-01-24 16:00:00', NULL),
(71, 'How to load data from json file in php', 'In this video you can find how to read json data from file and display that data on web page by using php. Source Code - http://www.webslesson.info/2016/06/how-to-load-data-from-json-file-in-php.html', 'Webslesson', '2019-01-24 05:00:00', NULL),
(72, 'Load JSON Data using Ajax getJSON Method', 'In this video you can find how to fetch or read json data from file using jquery Ajax get json method and display on web page without page refresh. Source Code - http://www.webslesson.info/2016/06/load-json-data-using-ajax-getjson-method.html', 'Webslesson', '2019-01-25 21:00:00', NULL),
(73, 'Add smooth scrolling by using Jquery Animate method', 'In this video I have covered jquery animate method and how to add smooth scrolling to webpage by using jquery animate method with scrollTop. Source Code - http://www.webslesson.info/2016/06/add-smooth-scrolling-by-using-jquery-animate-method.html', 'Webslesson', '2019-01-25 03:00:00', NULL),
(74, 'Ajax Autocomplete textbox using jQuery, PHP and MySQL', 'In this video you can find how to make Auto complete textbox using Ajax jquery with php and mysql. Autocomple textbox like google etc. jQuery Autocomplete Search using PHP, MySQL and Ajax. How to Autocomplete Textbox from Database in PHP, jQuery and MySQL. Source Code - http://www.webslesson.info/2016/06/ajax-autocomplete-textbox-using-jquery-php-and-mysql.html', 'Webslesson', '2019-01-26 18:00:00', NULL),
(75, 'Jquery Insert Form Data using Ajax serialize() method with php mysql', 'In this video you can find how to insert html form data using Jquery Ajax serialize() method. jQuery AJAX form data serialize using PHP. JQuery serialize() function with $.ajax() post for bigger HTML forms. Source Code - http://www.webslesson.info/2016/06/jquery-insert-form-data-using-ajax-serialize-method.html', 'Webslesson', '2019-01-28 05:00:00', NULL),
(76, 'Insert Form data using Jquery Post() Method with PHP Mysql', 'In this video I have explain Post() method of jquery by explaining how to insert data by using Post method of jqyery with php programming language with mysql database. Post method that loads a page from the server by using HTTP reques of POST. Source Code - http://www.webslesson.info/2016/06/insert-form-data-using-jquery-post-method-with-php-mysql.html', 'Webslesson', '2019-01-28 18:00:00', NULL),
(77, 'Connect MySQL Database in PHP via PDO - PHP Data Object', 'In this video, I show how to make mysql database connection in php by using PHP Data Objects(PDO). I have also the advantages of using PDO for Database connection and some basic introduction of PDO.', 'Webslesson', '2019-01-29 02:00:00', NULL),
(78, 'Insert data into Mysql in PHP using PDO - PHP Data Object', 'In this video you can find how to insert data into mysql database table in php by using PDO (PHP Data Object). PDO Video Tutorial for MySQL Developers. Why you Should be using PHP PDO for Database Access. PHP PDO Insert Data Into Database. How to use PHP Data Object - Beginners PHP PDO Tutorial.', 'Webslesson', '2019-01-29 20:00:00', NULL),
(79, 'Fetch Data from Mysql in PHP using PDO - PHP Data Object', 'In this video you can find how to fetch data from mysql table in php by using PDO(php data object modal). Learn Select Single records or fetch all records from table using PDO. I have use simple select query with exec() function and select single records with PDO prepare statement with execute function.', 'Webslesson', '2019-01-30 03:00:00', NULL),
(80, 'PDO (PHP Data Object) - Edit / Update Mysql Table data in PHP', 'Insert, Update, Delete with PDO. In this Video I have show update of mysql table data using pdo in php programming. PDO Tutorials for beginner. Basic of usage of PDO in update of records. PHP Pdo updating record to MySQL database table. PHP PDO Update Data in MySQL.', 'Webslesson', '2019-01-31 21:00:00', NULL),
(81, 'PDO (PHP Data Object) - Delete Mysql Table data in PHP', 'This video regarding how to delete mysql table records in php by using PDO (PHP Data Object). In this video I have show simple way to delete using exec() function and delete data by using prepare statement of PDO with execute() function. Insert, Update and Delete with PDO.', 'Webslesson', '2019-02-01 04:00:00', NULL),
(82, 'PHP Login Script using PDO with Session', 'PDO Login Script in PHP. In this video you can find how to make PHP login script using PDO(PHP Data Object). How to Create Login Page in PHP/MySQL using PDO Query. PHP Login System with PDO Connection. Login Script with PDO. Simple PHP Login system using PDO. Source Code - http://www.webslesson.info/2016/06/php-login-script-using-pdo-with-session.html', 'Webslesson', '2019-02-02 21:00:00', NULL),
(83, 'PHP Jquery Ajax : Insert Radio Button value on click', 'This video relates to how to insert radio button value in mysql data table in php programming language by using Jquery Ajax functionality. Add HTML Radio Button Value by PHP and jQuery. Get radio button value and sending through ajax to php. Source Code - http://www.webslesson.info/2016/06/php-jquery-ajax-insert-radio-button-value-on-click.html', 'Webslesson', '2019-02-02 07:00:00', NULL),
(84, 'How to Count a Array of Specific Words from String in PHP', 'This php video tutorial covers how to count array of specific words from a particular string in php. How many times array of word occurs in a string. Source Code - http://www.webslesson.info/2016/06/how-to-count-a-array-of-specific-words-from-string-in-php.html', 'Webslesson', '2019-02-04 20:00:00', NULL),
(85, 'Create dynamic JSON file in PHP Mysql', 'This video tutorial show you how to create dynamic json file from taking data from mysql database and convert that data into one array and convert that array to json file formate and thenafter create dynamic json file. Create dynamic JSON file in PHP Mysql.', 'Webslesson', '2019-02-04 02:00:00', NULL),
(86, 'Insert Checkbox values using Ajax Jquery in PHP', 'In this video tutorial I will show you how to insert checkbox values into mysql table using Ajax with jquery in php. How to Post multiple checkbox data to Mysql Table in PHP via jQuery ajax(). Source Code - http://www.webslesson.info/2016/06/insert-checkbox-values-using-ajax-jquery-in-php.html', 'Webslesson', '2019-02-04 20:00:00', NULL),
(87, 'How to Remove file from Server in PHP Programming Language', 'In this video you can find how to delete or remove file from server in php programming language. I have use php function like unlink() for remove or delete file from folder.', 'Webslesson', '2019-02-05 03:00:00', NULL),
(88, 'PHP Tutorial - Find the number of days, hours, minutes and seconds between two dates', 'In this php video tutorial you will learn how to calculate the number of days between two dates, number of hours between two dates, number of minutes between two dates and number of seconds between two dates.', 'Webslesson', '2019-02-05 21:00:00', NULL),
(89, 'Displaying text in Vertical Direction by using CSS with HTML', 'In this web development video tutorial series you can find how we can display text in vertical direction / orientation on background image using html and css. For displaying text in vertical direction I have set css property transform to rotate 90 degree. With the help of this css property can display text in vertical order. Source Code - http://www.webslesson.info/2016/07/displaying-text-in-vertical-direction-by-using-css.html', 'Webslesson', '2019-02-05 07:00:00', NULL),
(90, 'Show JSON Data in Jquery Datatables', 'In this web development video tutorial you can learn how to display json data in Jquery Datatable. For this I have using DataTable a table plugin for jquery. How to display JSON received from Datatables ajax call?. Source Code - http://www.webslesson.info/2016/07/show-json-data-in-jquery-datatables.html', 'Webslesson', '2019-02-06 15:00:00', NULL),
(91, 'Sliding Text on Images by using Jquery', 'In this video you can find one more functionality like sliding text on images can include in your website by using jquery. I have use slideToggle() method for sliding text on images. Source Code - http://www.webslesson.info/2016/07/sliding-text-on-images-by-using-jquery.html', 'Webslesson', '2019-02-07 07:00:00', NULL),
(92, 'How to Make Horizontal Menu using CSS and Jquery', 'In this video you can learn how to create simple horizontal menu by using html css with jquery. I have use simple ul and li html tag with css and in Jquery I have use hover() event with ul and li tag and I have also use this selector with fadeToggle() method. Source Code - http://www.webslesson.info/2016/07/how-to-make-horizontal-menu-using-css-and-jquery.html', 'Webslesson', '2019-02-07 21:00:00', NULL),
(93, 'How to make flashing button with CSS3 keyframes Animation', 'In this video you can learn how to create flashing button by using css3 @keyframes animation. CSS3 Flashing and Pulse Effects keyframes Animation Video Tutorial. How to make flashing or glowing button using @keyframes animation in CSS3. Source Code - http://www.webslesson.info/2016/07/how-to-make-flashing-button-with-css3-keyframes-animation.html', 'Webslesson', '2019-02-08 06:00:00', NULL),
(94, 'Get Maximum Numeric value from Associative Array in PHP', 'In this video you can learn how to find the maximum numeric value from associative array in php. In this video I have store specific keys value into one array and from that array I will find maximum value by using max() function of array. Source Code - http://www.webslesson.info/2016/07/get-maximum-numeric-value-from-associative-array-in-php.html', 'Webslesson', '2019-02-09 17:00:00', NULL),
(95, 'How to make Zebra Stripes Table with PHP Mysql', 'How to make zebra stripes table from data get from mysql table in php. I will make zebra stripe table without using any javascript jquery or even css. I will only use simple html table with php to make zebra stripe table. Source Code - http://www.webslesson.info/2016/07/how-to-make-zebra-stripes-table-with-php-mysql.html', 'Webslesson', '2019-02-10 09:00:00', NULL),
(96, 'How to Get File Extension in PHP', 'This video learn you how can we get the extension of file in php programming language. If you suppose work on upload file to your web application and that time you want to check uploaded file is allowed or not on your web application. This things you can figure out on the basis of that file extension.', 'Webslesson', '2019-02-11 17:00:00', NULL),
(97, 'Server Side Form Validation in PHP Programming Language', 'Server Side Form validation is also import part in php. Because some of the browser is still not supporting client side form validation so it is secure if also do server side form valition in your web application which build in php programming language. Source Code - http://www.webslesson.info/2016/07/server-side-form-validation-in-php-programming-language.html', 'Webslesson', '2019-02-12 06:00:00', NULL),
(98, 'PHP Array Functions - array() Function', 'In this video tutorial you can learn about PHP array() function. An Array is a variable which store multiple values in a single variable. In PHP array can be define by array() function. Array() function is used to create array variable in PHP. Source - http://www.webslesson.info/2016/07/php-array-functions-array-function.html', 'Webslesson', '2019-02-13 16:00:00', NULL),
(99, 'PHP Array Functions - array_change_key_case() Function', 'This video regarding PHP Array function like array_change_key_case(). This function will convert the keys case to lowercase or uppercase. It will return false if the array is not array which have used as parameter in this function.', 'Webslesson', '2019-02-13 17:37:30', NULL),
(100, 'PHP Array Functions - array_chunk() Function', 'If you want to divide one php array into different block of fixed size array, then you can use array_chunk() function of PHP. This PHP Array function return multidimensional array from single array.', 'Webslesson', '2019-02-15 08:00:00', NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `post`
--
ALTER TABLE `post`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `post`
--
ALTER TABLE `post`
  MODIFY `id` mediumint(8) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=101;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
